default: &default
  adapter: postgresql
  encoding: utf-8
  username: admin
  password: 123456
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blogging_development

test:
  <<: *default
  database: blogging_test

production:
  <<: *default
  database: collabTesting_production
  username: collabTesting
  password: <%= ENV['COLLABTESTING_DATABASE_PASSWORD'] %>
